import { getPublicBatch } from "@/db/queries/production";
import { notFound } from "next/navigation";

/**
 * Public best-before page. The QR codes on physical labels resolve here; any
 * customer who scans a printed label with their phone camera lands on this
 * page with no login required. Reads via the SECURITY DEFINER SQL function
 * `get_public_batch()` which exposes only customer-safe fields (no costs,
 * no inventory data, no other batches).
 */
export default async function PublicBatchPage({
  params,
}: {
  params: Promise<{ batchId: string }>;
}) {
  const { batchId } = await params;
  const batch = await getPublicBatch(batchId);
  if (!batch) notFound();

  const fmtDate = (d: Date) =>
    d.toLocaleString("en-AE", {
      weekday: "short",
      day: "numeric",
      month: "long",
      hour: "numeric",
      minute: "2-digit",
    });

  const hoursToExpiry = Math.max(
    0,
    Math.round((batch.expiresAt.getTime() - Date.now()) / (1000 * 60 * 60)),
  );

  const freshnessLabel =
    batch.status === "expired" || batch.expiresAt.getTime() < Date.now()
      ? { text: "Past best-before — please discard", tone: "destructive" as const }
      : hoursToExpiry < 24
        ? { text: `Best within ${hoursToExpiry}h`, tone: "warning" as const }
        : { text: "Fresh", tone: "good" as const };

  const toneClass =
    freshnessLabel.tone === "destructive"
      ? "bg-red-50 text-red-700 ring-red-100"
      : freshnessLabel.tone === "warning"
        ? "bg-amber-50 text-amber-700 ring-amber-100"
        : "bg-emerald-50 text-emerald-700 ring-emerald-100";

  return (
    <div className="min-h-svh bg-stone-50 flex items-start sm:items-center justify-center p-6">
      <div className="w-full max-w-md bg-white rounded-2xl shadow-sm border border-stone-200 overflow-hidden">
        <div className="px-6 pt-7 pb-5 text-center">
          <div className="text-[11px] font-semibold tracking-[0.2em] text-stone-400 uppercase">
            Crazy Brownies · Dubai
          </div>
          <h1 className="text-xl sm:text-2xl font-semibold tracking-tight text-stone-900 mt-1.5 leading-tight">
            {batch.productName}
          </h1>
          <div className="text-xs text-stone-500 mt-1">{batch.category}</div>
        </div>

        <div className={`mx-6 rounded-lg ring-1 ring-inset ${toneClass} px-4 py-3 text-center`}>
          <div className="text-sm font-semibold">{freshnessLabel.text}</div>
        </div>

        <dl className="px-6 py-5 grid grid-cols-1 gap-3 text-sm">
          <Row label="Baked" value={fmtDate(batch.bakedAt)} />
          <Row label="Best before" value={fmtDate(batch.expiresAt)} />
          <Row label="Batch" value={batch.batchCode} mono />
        </dl>

        <div className="px-6 pb-6 text-[11px] text-stone-400 text-center">
          This page is generated by Crazy Brownies&apos; freshness tracker.
        </div>
      </div>
    </div>
  );
}

function Row({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="flex items-center justify-between gap-4 border-b last:border-b-0 border-stone-100 pb-2.5 last:pb-0">
      <dt className="text-stone-500 uppercase tracking-wide text-[11px]">{label}</dt>
      <dd className={`text-stone-900 ${mono ? "font-mono text-xs" : "tabular-nums"}`}>{value}</dd>
    </div>
  );
}

export const dynamic = "force-dynamic";
